name: ubuntu-home-server

networks:
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

# Include the individual docker compose files for each service
# TODO: Create a script that auto generates the include paths
include:
  # Applications
  - $APPLICATIONS_DIR/excalihome.yaml # Local manage Excalidraw app
  - $APPLICATIONS_DIR/homebox.yaml # Asset organization tool
  - $APPLICATIONS_DIR/karakeep.yaml # Bookmark management tool
  - $APPLICATIONS_DIR/tally.yaml # Board games management tool

  # Infrastructure
  - $INFRASTRUCTURE_DIR/portainer.yaml # Docker management UI
  - $INFRASTRUCTURE_DIR/traefik.yaml # Domain routing, reverse proxy and certificate manager
  - $INFRASTRUCTURE_DIR/uptimekuma.yaml # Uptime monitoring

  # IoT
  - $IOT_DIR/dynsec-admin.yaml # MQTT dynamic security admin web interface
  - $IOT_DIR/homeassistant.yaml # Home automation powerhouse
  - $IOT_DIR/matter-server.yaml # Local Matter broker
  - $IOT_DIR/mosquitto.yaml # Local MQTT broker
  - $IOT_DIR/music-assistant.yaml # Centralize media manager
  - $IOT_DIR/zigbee2mqtt.yaml # Zigbee coordinator
