# Home Assistant allows me to manage all things IoT and home automation.
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      # Persistant data.
      # * :rw - Read and Write.
      - $DOCKER_DATA_DIR/homeassistant:/config:rw

      # Local Time.
      # * :rw - Read and Only.
      - $DOCKER_LOCAL_DIR
      
      # ! Learn More
      # * :rw - Read Only.
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=$TZ
    depends_on:
      - mosquitto
      - zigbee2mqtt
    privileged: true
    network_mode: host
    extra_hosts:
      - mosquitto:172.18.0.100
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.homeassistant-router.rule=Host(`ha.homeserver.lukan.rocks`)
      - traefik.http.routers.homeassistant-router.entrypoints=web,websecure
      - traefik.http.routers.homeassistant-router.tls=true
      - traefik.http.routers.homeassistant-router.tls.certresolver=letsencrypt
      - traefik.http.routers.homeassistant-router.service=homeassistant-services
      - traefik.http.services.homeassistant-services.loadbalancer.server.port=8123