# Home Assistant allows me to manage all things IoT and home automation. - https://www.home-assistant.io/

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.8
    restart: unless-stopped
    depends_on:
      - easy-mqtt
      - zigbee2mqtt
      - matter-server
    privileged: true
    network_mode: host
    security_opt: no-new-privileges:true
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKER_DATA_DIR/homeassistant:/config:rw
      - $DOCKER_LOCAL_DIR:ro
      - $DOCKER_SOCK_DIR:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant-router.rule=Host(`ha.homeserver.lukan.rocks`)
      - traefik.http.routers.homeassistant-router.entrypoints=web,websecure
      - traefik.http.routers.homeassistant-router.tls=true
      - traefik.http.routers.homeassistant-router.tls.certresolver=letsencrypt
      - traefik.http.routers.homeassistant-router.service=homeassistant-services
      - traefik.http.services.homeassistant-services.loadbalancer.server.port=8123
    extra_hosts:
      - easy-mqtt:172.18.0.100