# Mosquitto is used as my local MQTT broker - https://mosquitto.org/

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.1.2-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKER_DATA_DIR/mosquitto/config:/mosquitto/config:rw
      - $DOCKER_DATA_DIR/mosquitto/data:/mosquitto/data:rw
      - $DOCKER_LOGS_DIR/mosquitto:/mosquitto/log:rw
    networks:
      traefik-proxy:
        ipv4_address: 172.18.0.100 # fixed ip to be easily targeted | Maybe is unecessary, review later
    labels:
      - traefik.enable=false
    ports:
      - 1883:1883