# Mosquitto is used as my local MQTT broker
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      # Configuration Files.
      # * :rw - Read and Write.
      - $DOCKER_DATA_DIR/mosquitto/config:/mosquitto/config:rw
      
      # Persistant data.
      # * :rw - Read and Write.
      - $DOCKER_DATA_DIR/mosquitto/data:/mosquitto/data:rw

      # Logs.
      # * :rw - Read and Write.
      - $DOCKER_LOGS_DIR/mosquitto:/mosquitto/log:rw
    networks:
      traefik-proxy:
        ipv4_address: 172.18.0.100 # fixed ip to be easily targeted | Maybe is unecessary, review later
    ports:
      - 1883:1883
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - traefik.enable=false