# Music Assistant is a media library manager that connects streaming services to connected speakers. - https://www.music-assistant.io/installation/

services:
  music-assistant-server:
    container_name: music-assistant-server
    image: ghcr.io/music-assistant/server:2.9.8
    restart: unless-stopped
    depends_on:
      - homeassistant
    privileged: true
    network_mode: host
    security_opt: apparmor:unconfined
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKER_DATA_DIR/music-assistant-server:/data/:rw
    # labels:
      # - traefik.enable=true
      # - traefik.http.routers.musicassistant-router.rule=Host(`ma.homeserver.lukan.rocks`)
      # - traefik.http.routers.musicassistant-router.entrypoints=web,websecure
      # - traefik.http.routers.musicassistant-router.tls=true
      # - traefik.http.routers.musicassistant-router.tls.certresolver=letsencrypt
      # - traefik.http.routers.musicassistant-router.service=musicassistant-services
      # - traefik.http.services.musicassistant-services.loadbalancer.server.port=8123
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
