# Home Assistant allows me to manage all things IoT and home automation.
services:
  music-assistant-server:
    container_name: music-assistant-server
    image: ghcr.io/music-assistant/server:latest
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      # Persistant data.
      # * :rw - Read and Write.
      - $DOCKER_DATA_DIR/music-assistant-server:/data/:rw
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    environment:
      - TZ=$TZ
    privileged: true
    network_mode: host
    # labels:
      # - com.centurylinklabs.watchtower.enable=true
      # - traefik.enable=true
      # - traefik.http.routers.homeassistant-router.rule=Host(`ma.homeserver.lukan.rocks`)
      # - traefik.http.routers.homeassistant-router.entrypoints=web,websecure
      # - traefik.http.routers.homeassistant-router.tls=true
      # - traefik.http.routers.homeassistant-router.tls.certresolver=letsencrypt
      # - traefik.http.routers.homeassistant-router.service=homeassistant-services
      # - traefik.http.services.homeassistant-services.loadbalancer.server.port=8123
