# Zigbee2MQTT manages all my zigbee devices.
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      # Persistant data.
      # * :rw - Read and Write.
      - $DOCKER_DATA_DIR/zigbee2mqtt:/app/data:rw

      # Local Time.
      # * :rw - Read and Write.
      - $DOCKER_LOCAL_DIR

      # Logs.
      # * :rw - Read and Write.
      - $DOCKER_LOGS_DIR/zigbee2mqtt:/app/data/log:rw
    depends_on:
      - mosquitto
    networks:
      - traefik-proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.zigbee2mqtt-router.rule=Host(`z2m.homeserver.lukan.rocks`)
      - traefik.http.routers.zigbee2mqtt-router.entrypoints=web,websecure
      - traefik.http.routers.zigbee2mqtt-router.tls=true
      - traefik.http.routers.zigbee2mqtt-router.tls.certresolver=letsencrypt
      - traefik.http.routers.zigbee2mqtt-router.service=zigbee2mqtt-services
      - traefik.http.services.zigbee2mqtt-services.loadbalancer.server.port=8080