services:
  zone-configurator:
    container_name: zone-configurator
    image: everythingsmarthome/everything-presence-mmwave-configurator:2.2.4
    restart: unless-stopped
    depends_on:
      - homeassistant
    security_opt: no-new-privileges:true
    env_file: $DOCKER_SECRETS_DIR/esphome
    volumes:
      - $DOCKER_DATA_DIR/zone-configurator:/config
    networks: traefik-proxy
    extra_hosts: host.docker.internal:host-gateway
    labels:
      - traefik.enable=true
      - traefik.http.routers.everythingsmarthome-router.rule=Host(`esh.homeserver.lukan.rocks`)
      - traefik.http.routers.everythingsmarthome-router.entrypoints=web,websecure
      - traefik.http.routers.everythingsmarthome-router.tls=true
      - traefik.http.routers.everythingsmarthome-router.tls.certresolver=letsencrypt
      - traefik.http.routers.everythingsmarthome-router.service=everythingsmarthome-services
      - traefik.http.services.everythingsmarthome-services.loadbalancer.server.port=42069