# Traefik handles the reverse proxy and certificates validation. - https://doc.traefik.io/traefik/

services:
  traefik:
    container_name: traefik
    image: docker.io/library/traefik:v3.7.7
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    env_file: # Passwords and Secrets only file
      - $DOCKER_SECRETS_DIR/traefik_secrets
    volumes:
      - $DOCKER_SOCK_DIR:ro
      - $DOCKER_LOCAL_DIR:ro
      - $DOCKER_CONFIG_DIR/traefik/config.yaml:/etc/traefik/traefik.yaml:ro
      - $DOCKER_DATA_DIR/letsencrypt:/letsencrypt:rw
      - $DOCKER_LOGS_DIR/traefik:/var/log/traefik:rw
    healthcheck: # requires `ping: {}` in config/traefik/config.yaml
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      start_period: 15s
      retries: 3
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-router.rule=Host(`traefik.homeserver.lukan.rocks`)
      - traefik.http.routers.traefik-router.entrypoints=web,websecure
      - traefik.http.routers.traefik-router.tls=true
      - traefik.http.routers.traefik-router.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-router.service=api@internal
      - traefik.http.services.api@internal.loadbalancer.server.port=8080