# UptimeKuma allows me to easily check the status of my services.
services:
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      # Persistant data.
      # * :rw - Read and Write.
      - $DOCKER_DATA_DIR/uptimekuma:/app/data:rw
    environment:
      - TZ=$TZ
    depends_on:
      - traefik
    networks:
      - traefik-proxy
    labels:
      # Allows this conteiner to be exposed by traefik.
      - traefik.enable=true
      
      # Defines the DNS route.
      - traefik.http.routers.uptimekuma-router.rule=Host(`uptimekuma.homeserver.lukan.rocks`)
      
      # Defines the allowed entrypoints for this application.
      - traefik.http.routers.uptimekuma-router.entrypoints=web,websecure
      - traefik.http.routers.uptimekuma-router.tls=true
      - traefik.http.routers.uptimekuma-router.tls.certresolver=letsencrypt