# UptimeKuma allows me to easily check the status of my services. - https://github.com/louislam/uptime-kuma

services:
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKER_DATA_DIR/uptimekuma:/app/data:rw
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptimekuma-router.rule=Host(`uptimekuma.homeserver.lukan.rocks`)
      - traefik.http.routers.uptimekuma-router.entrypoints=web,websecure
      - traefik.http.routers.uptimekuma-router.tls=true
      - traefik.http.routers.uptimekuma-router.tls.certresolver=letsencrypt
