# Local manage Excalidraw app - https://github.com/LukanRocks/excalihome

services:
  excalihome:
    container_name: excalihome
    image: ghcr.io/lukanrocks/excalihome:latest
    restart: unless-stopped
    security_opt: no-new-privileges:true
    volumes:
      - $DOCKER_DATA_DIR/excalihome:/app/data:rw
    networks: traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalihome-router.rule=Host(`excalihome.homeserver.lukan.rocks`)
      - traefik.http.routers.excalihome-router.entrypoints=web,websecure
      - traefik.http.routers.excalihome-router.tls=true
      - traefik.http.routers.excalihome-router.tls.certresolver=letsencrypt
