# Homebox allows to keep track of all my stuff.
services:
  homebox:
    container_name: homebox
    image: ghcr.io/sysadminsmedia/homebox:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKER_DATA_DIR/homebox:/data:rw
    environment:
      - TZ=$TZ
      - HBOX_MODE="production"
      - HBOX_OPTIONS_ALLOW_REGISTRATION=false
      - HBOX_OPTIONS_AUTO_INCREMENT_ASSET_ID=true
      - HBOX_LOG_LEVEL="warn" # trace, debug, info, warn, error, critical
    networks:
      - traefik-proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.homebox-router.rule=Host(`homebox.homeserver.lukan.rocks`)
      - traefik.http.routers.homebox-router.entrypoints=web,websecure
      - traefik.http.routers.homebox-router.tls=true
      - traefik.http.routers.homebox-router.tls.certresolver=letsencrypt