# Homebox allows to keep track of all my stuff.
services:
  homebox:
    container_name: homebox
    image: ghcr.io/sysadminsmedia/homebox:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - $DOCKER_CONFIG_DIR/homebox/config.env
    volumes:
      - $DOCKER_DATA_DIR/homebox:/data:rw
    environment:
      - TZ=$TZ
    depends_on:
      - traefik
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homebox-router.rule=Host(`homebox.homeserver.lukan.rocks`)
      - traefik.http.routers.homebox-router.entrypoints=web,websecure
      - traefik.http.routers.homebox-router.tls=true
      - traefik.http.routers.homebox-router.tls.certresolver=letsencrypt